#ifndef _AVRPROGINSTRUCTIONS_H_
#define _AVRPROGINSTRUCTIONS_H_

// from ATmega169 datasheet, section "Serial Programming Instruction Set"
#define AVRSPI_READ_FUSE_BITS_BYTE1			0x50
#define AVRSPI_READ_FUSE_BITS_BYTE2 		0x00
#define AVRSPI_READ_EXT_FUSE_BITS_BYTE2		0x08
#define AVRSPI_READ_FUSE_HIGH_BITS_BYTE1	0x58
#define AVRSPI_READ_FUSE_HIGH_BITS_BYTE2	0x08
#define AVRSPI_READ_LOCK_BITS_BYTE2			0x00

#define AVRSPI_WRITE_LOCK_BITS_BYTE1		0xAC
#define AVRSPI_ERASE_CHIP_BYTE2_MASK		0xE0
#define AVRSPI_ERASE_CHIP_BYTE2_MATCH		0x80
#define AVRSPI_WRITE_LOCK_BITS_BYTE2_MATCH	0xE0
#define AVRSPI_WRITE_LOCK_BITS_BYTE2_MASK	0xE0
#define AVRSPI_WRITE_FUSE_BITS_BYTE2		0xA0
#define AVRSPI_WRITE_FUSE_HIGH_BITS_BYTE2	0xA8
#define AVRSPI_WRITE_EXT_FUSE_BITS_BYTE2	0xA4

#define AVRSPI_READ_SIGNATURE_BYTE1			0x30
#define AVRSPI_READ_CALIBRATION_BYTE1		0x38

#define AVRSPI_READ_PROGMEM_LOW_BYTE1		0x20
#define AVRSPI_READ_PROGMEM_HIGH_BYTE1		0x28

#define AVRSPI_LOAD_PROGMEM_PAGE_HIGH_BYTE1	0x40
#define AVRSPI_LOAD_PROGMEM_PAGE_LOW_BYTE1	0x48

#define AVRSPI_READ_EEPROM_BYTE1			0xA0
#define AVRSPI_WRITE_EEPROM_BYTE1			0xC0

#define AVRSPI_WRITE_FLASH_PAGE_BYTE1		0x4C

#endif
